### ISSUE TITLE
doesn't work with diesel 2.0.0-rc.0

### ISSUE THREAD

**Issue by vcombey** [adwhit/diesel-derive-enum#73]
when using master with diesel 2.0.0-rc.0,
On every DbEnum invocation, I got:
```
error[E0433]: failed to resolve: could not find `sql_types` in `schema`
   --> src/calendar/get.rs:273:39
    |
273 |     #[derive(Debug, Clone, PartialEq, DbEnum, Serialize, Deserialize)]
    |                                       ^^^^^^ could not find `sql_types` in `schema`
    |
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
````

**Comment by Ten0** [comment]
I think that error would happen if you were to use the old Diesel CLI with the new diesel/diesel-derive-enum.

Using [diesel cli 2.0.0-rc.0](https://crates.io/crates/diesel_cli/2.0.0-rc.0) should solve that issue.
